version: "3.3"

services:
  portfolio:
    image: ghcr.io/thibault-cne/portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`thibault-cne.fr`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_traefik"
    networks:
      - traefik

networks:
  traefik:
    external: true
    name: traefik_traefik
